main/example.spec.ts(508,55): error TS6133: 'n' is declared but its value is never read. main/example.spec.ts(514,5): error TS2552: Cannot find name 'n_days_from_script_launc'. Did you mean 'n_days_from_script_launch'?