Better? Worse?
```
main/example.spec.ts(1148,9): error TS2322: Type 'string | undefined' is not assignable to type 'string'.
  Type 'undefined' is not assignable to type 'string'.
main/example.spec.ts(1151,5): error TS2353: Object literal may only specify known properties, and 'raw_text_lines' does not exist in type 'InterpretExistingBooking[]'.
main/example.spec.ts(1155,49): error TS2304: Cannot find name 'str'.
main/example.spec.ts(1586,82): error TS2339: Property 'new' does not exist on type 'MapConstructor'.
main/example.spec.ts(1753,9): error TS7052: Element implicitly has an 'any' type because type 'Map<string, InterpretExistingBooking[]>' has no index signature. Did you mean to call 'all_bookings_by_username.set'?
main/example.spec.ts(1763,11): error TS7052: Element implicitly has an 'any' type because type 'Map<string, InterpretExistingBooking[]>' has no index signature. Did you mean to call 'all_bookings_by_username.get'?
main/example.spec.ts(1806,8): error TS6133: 'test_existingbooking' is declared but its value is never read.
main/example.spec.ts(1809,9): error TS2740: Type 'InterpretExistingBooking[]' is missing the following properties from type 'InterpretExistingBooking': raw_text_lines, raw_ariasnapshot, raw_innerhtml, booking_person_fullname, and 2 more.
main/example.spec.ts(1809,80): error TS2552: Cannot find name 'text_existingbooking'. Did you mean 'test_existingbooking'?
…
main/example.spec.ts(1154,5): error TS2322: Type 'string | undefined' is not assignable to type 'string'.
  Type 'undefined' is not assignable to type 'string'.
main/example.spec.ts(1763,11): error TS2532: Object is possibly 'undefined'.
```