error TS2468: Cannot find global value 'Promise'.
main/example.spec.ts(24,74): error TS2705: An async function or method in ES5 requires the 'Promise' constructor. Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your '--lib' option.